### ISSUE TITLE
Lack of feature coverage table

### ISSUE THREAD

**Issue by emg110** [algorand/pyteal#103]
## Problem

Since PyTeal does not update in sync with Algorand releases teal code and version therefore a coverage table can help every dev to immediately understand which functionalities of teal is supported and which ones are not.

## Solution

Creating, updating and maintaining a TEAL coverage (Or a not yet covered table if that's the case) table in README.md

## Urgency

Medium

**Comment by jasonpaulos** [comment]
Are you aware of this table? https://pyteal.readthedocs.io/en/stable/versions.html

Or are you looking for a more detailed table that shows support for each individual feature?

**Comment by emg110** [comment]
I'm aware of that version coverage and yes exactly good point , I meant **Feature Coverage**.

**Comment by algoanne** [comment]
closing this; the goal is for pyteal to stay up-to-date at all times (it currently is and we have it in our process to make sure it stays that way, hopefully we succeed going forward).
