### ISSUE TITLE
Dynamic Array Reference

### ISSUE THREAD

**Issue by barnjamin** [algorand/pyteal#109]
## Problem

I'd like to be able to reference the elements of the Txn.application_args array dynamically using the looping construct with ScratchVars.  Currently this is not supported but I see support is available in the Gtxn array.

example of what I'd like to do:
```python
def set_properties(acct, args, start):
    idx = ScratchVar()

    init = idx.store(Int(start))
    cond = idx.load()<args.length()
    step = idx.store(idx.load() + Int(2))

    return Seq([
        For(init, cond, step).Do(
            App.localPut(acct, args[idx.load()], args[idx.load() + Int(1)])
        ),
        Int(1)
    ])

```
This may be supported in some way but I can't seem to find it.

## Solution

Accept the Union[int,Expr] in the Txn array items `__getitem__` call

**Comment by barnjamin** [comment]
https://github.com/algorand/go-algorand/pull/2847 this may be a prerequisite?

**Comment by jasonpaulos** [comment]
This will be added for TEAL 5.
