### ISSUE TITLE
Research: Add TEAL comments corresponding to PyTEAL filename & line number

### ISSUE THREAD

**Issue by plasmatech8** [algorand/pyteal#116]
## Problem

When we compile PyTEAL code to TEAL, there is no way to figure out which line of TEAL corresponds to which line in PyTEAL.

This is a problem when:
* We send a transaction and receive an assert error (or err error), but cannot figure out which part of our PyTEAL is responsible for this error. 
* We simply want to examine part of our TEAL code

For example, an assert statement returns an error stating that the assert failed on line pc=23, but then we need to figure out where in the PyTEAL this corresponds to.

## Solution

Add an option in `compileTeal(comments=True)` which inserts TEAL comments corresponding to the PyTEAL filename (not including full path) and line number (trace).

e.g.
```teal
# File "my_contract.py", line 19, in compile\n
```
Note: I can see the definition trace list in the PyTEAL objects (i.e. `Int(0).trace` or `Int(0).getDefinitionTrace()`)

If possible, add a TEAL comment for every PyTEAL node, otherwise simply add a comment directly above the assert/err opcodes. 

## Dependencies

Notes: 
* To make this work, it seems that code needs to be added in `compileTeal`, `sortBlocks` and `flattenBlocks` to pass the trace string over multiple steps in `compileTeal` - between the multiple syntax trees (ast>start>order>teal>lines). 
* I have not examined the code enough to understand how to appropriately pass the data. 
* (Alternatively, it might be possible to insert some comments post compilation by scanning the TEAL code and labeling opcodes based on order - but I am not sure if that works or is particularly good practice).

## Urgency

Low urgency. 

It is a quality-of-life / self-documentation improvement.

**Comment by plasmatech8** [comment]
Perhaps it is possible to create a `generateMaps` function which could create a map from pc -> PyTEAL line number. 
```json
{
  "4": { "file": "my_contract.py", "method": "compile", "line": 16},
  "...": "..."
}
```

**Comment by jasonpaulos** [comment]
I agree that it would be very beneficial to provide a source map from the generated TEAL source file to the PyTeal program.

But unfortunately it's outside of PyTeal's scope to provide a mapping from the bytecode pc to a PyTeal program, since this requires knowledge of how that bytecode is assembled which PyTeal does not have.

Though perhaps `goal` could be extended to generate a source map from compiled TEAL bytecode to TEAL source, and this could be used in conjunction with a sourcemap from PyTeal -> TEAL source to document the entire compilation chain?

**Comment by barnjamin** [comment]
>Though perhaps goal could be extended to generate a source map from compiled TEAL bytecode to TEAL source, and this could be used in conjunction with a sourcemap from PyTeal -> TEAL source to document the entire compilation chain?

I've got a PR out for this but its meh: https://github.com/algorand/go-algorand/pull/2921

**Comment by algoanne** [comment]
taking this ticket as the research part of this initiative, since it's not clear how we will approach this. We agree this is an important problem to solve.

**Comment by algoanne** [comment]
closing this research and continuing the work in #449
