### ISSUE TITLE
Support for ECDSA 

### ISSUE THREAD

**Issue by barnjamin** [algorand/pyteal#125]
## Problem

The ECDSA related opcodes are in the opcode list but not exposed in PyTeal
https://github.com/algorand/pyteal/blob/81275c5c2024d997aa1b5122f7298545e1e347e4/pyteal/ir/ops.py#L149-L151

I'm not sure if this is intentional and they're not meant to be used by a broader audience but seen at least a couple people asking about how to use them.

**Comment by jasonpaulos** [comment]
Good point, PyTeal should expose these operations as well. The only issue is `ecdsa_pk_decompress` and `ecdsa_pk_recover` push 2 values to the stack, and the only solution we currently have to deal with this is `MaybeValue`, which has been a source of confusion for many developers.

If possible, I would like these expressions to avoid using a mechanism like `MaybeValue`, so it requires some thought.

**Comment by jannotti** [comment]
How does divmodw deal with all its return values?

**Comment by tzaffi** [comment]
@barnjamin 's find. Usage in the wild _before_ this issue was solved:
https://github.com/certusone/wormhole/blob/jsiegel/algorand/staging/algorand/teal/wormhole/pyteal/vaa-verify.py#L59-L65
