### ISSUE TITLE
Periodic payment smart signature can be used multiple times within the same block

### ISSUE THREAD

**Issue by jordan-public** [algorand/pyteal#143]
### Subject of the issue

 
The example smart signature https://github.com/algorand/pyteal/blob/master/examples/signature/periodic_payment.py can be called twice in the same block, thus double-paying the intended amount.

### Your environment
Same as the example.

### Steps to reproduce

1. When calling from the client using "acl.send_transaction(lstx)", repeat this twice.
2. In the block where Txn.first_valid() % tmpl_period == Int(0), this transaction gets executed twice.

### Expected behaviour
Single paying (some code should prevent the transaction from running twice within a block).
This could be an assertion that last succesful transaction was more than a block ago.

### Actual behaviour
Double-paying within the same period.

**Comment by jasonpaulos** [comment]
@jordan-public the lease field prevents the second transaction from being accepted by the network. See this article for more info: https://developer.algorand.org/articles/leased-transactions-securing-advanced-smart-contract-design/

**Comment by jordan-public** [comment]
Oops, I had removed it not understanding what it was for. 

Maybe you can mention this in the sample explanation.

Thanks,
Jordan
