### ISSUE TITLE
Any update on JavascriptTeal or JsTeal?

### ISSUE THREAD

**Issue by Samuellyworld** [algorand/pyteal#155]
## Problem

any update to use javascript with Teal?

## Solution

it helps more developers work with teal more

## Urgency

any time.

**Comment by jasonpaulos** [comment]
There is this repo made by a community member: https://github.com/DavidSeptimus/jsteal

**Comment by Samuellyworld** [comment]
Thank you for this!

**Comment by Samuellyworld** [comment]
but would appreciate one being managed by algorand itself
