### ISSUE TITLE
Optimize `ScratchVar`s into stack variables

### ISSUE THREAD

**Issue by jasonpaulos** [algorand/pyteal#173]
## Summary

`ScratchVar`s are frequently used as variables in PyTeal code. In fact, they are the only way to express mutable values (besides persistent state).

But in TEAL, the stack can also be used to contain temporary mutable "variables". This issue is to make PyTeal's compiler convert scratch slots to stack variables when possible -- essentially optimizing away the slot usage.

This has two benefits:
1. Less scratch slots will be required (allowing programs to be more complex)
2. Scratch slots which can be turned into stack variables will be more efficient, since they'll use less opcodes

## Scope
<I'll fill in more details later>

**Comment by michaeldiamant** [comment]
Closing - Released in https://github.com/algorand/pyteal/releases/tag/v0.11.0.
