### ISSUE TITLE
Support passing ABI types to and from subroutines

### ISSUE THREAD

**Issue by jasonpaulos** [algorand/pyteal#179]
## Summary

#154 introduces ABI type support in PyTeal. Following that, it would be incredibly useful for subroutines to be able to take ABI types as arguments and to be able to return an ABI type.

The most obvious way to denote this would be to use the ABI type as an annotation to a subroutine's arguments or return value. 

## Scope

If a subroutine has ABI type arguments, then the compiler should pass a value representing the ABI type onto the stack (this is not necessarily the encoded value, since types like Uint8-64 are more naturally represented as TEAL uint64s)

Due to the fact that `abi.Type`s are not `Expr`s, I suspect that an `abi.ComputedType` will be needed to wrap the return value. For example:

```python
from pyteal import *

@Subroutine() # a return declaration here is not necessary anymore?
def mySubroutine(a: abi.Uint64, b: abi.Uint64) -> abi.ComputedType[abi.Uint64]:
    # TODO: somehow return a + b
```

Alternatively, we could provide a way to store the return value into an argument representing the output. Something like:

```python
@Subroutine() # a return declaration here is not necessary anymore?
def mySubroutine(a: abi.Uint64, b: abi.Uint64, *, output: abi.Uint64) -> Expr:
    return output.set(a.get() + b.get())
```

**Comment by ahangsu** [comment]
One minor problem: according to subroutine implementation, the following snippet cannot run;
```python
@Subroutine() # a return declaration here is not necessary anymore?
def mySubroutine(a: abi.Uint64, b: abi.Uint64, *, output: abi.Uint64) -> Expr:
    return output.set(a.get() + b.get())
```
because `output` here is `KEYWORD_ONLY`. A solution is to remove `*` and let `output` sits at the end of arguments.

Another problem I am thinking of: we may want to extend the check from Zeph's implementation: which essentially constrain annotated arguments/returns to be `Expr`. We want to additionally allow for `abi` types specification here?

**Comment by jasonpaulos** [comment]
> One minor problem: according to subroutine implementation, the following snippet cannot run;
> 
> ...
> 
> because `output` here is `KEYWORD_ONLY`. A solution is to remove `*` and let `output` sits at the end of arguments.

Yes I did that on purpose in order to make `output` unique. In order to make it work, we would need to allow an exception for this specific keyword argument, and if present, we'd know that the subroutine returns an ABI value. This is just a suggestion though, you might be able to come up with a better interface.

> Another problem I am thinking of: we may want to extend the check from Zeph's implementation: which essentially constrain annotated arguments/returns to be `Expr`. We want to additionally allow for `abi` types specification here?

Yes, this issue should expand the allowable types in a subroutine to include all `abi` types as well.

> If I follow along with the idea in issue description, then not only return type, the argument abi types will need to be "wrapped" to be looking like an `Expr` to `isinstance`. (which eventually looks like `ExprifyABI[abi.uint64]`)

I think you're talking about how the arguments are prepared when a subroutine is called? If that's the case, I hope we can add more code to accept either `Expr` or an `abi.Type` instance (checked against the subroutine definition's types). If it's an `abi.Type`, then you could push the value contained in its internal `ScratchVar` onto the stack to act as the argument at runtime. It should be possible to then load this into another instance of the same `abi.Type` in the code that implements the subroutine's body.

**Comment by ahangsu** [comment]
After reading Zeph's stores/loads PR, I kind of picture how this should be done:
- Essentially if we are passing abiTypes, we are still passing "reference to a scratch variable".
- Router will take care of the transformation from bytes (txna ApplicationArgs i) to abiType (ref to scratch var).
- This issue should take care of the subroutine restriction on input arg annotation (and subroutine return annotation).

**Comment by tzaffi** [comment]
@ahangsu - that code is still a moving target. Have a look at[ Jason's comment](https://github.com/algorand/pyteal/pull/183#discussion_r798994911) and make sure your approach still makes sense (I'm guessing it still does)

**Comment by ahangsu** [comment]
> that code is still a moving target. Have a look at [Jason's comment](https://github.com/algorand/pyteal/pull/183#discussion_r798994911) and make sure your approach still makes sense (I'm guessing it still does)

I think the previous approach (should) still makes senses, but let's see how it proceeds and I might change my thoughts...
