### ISSUE TITLE
Update Docs on Subroutines and ScratchVariables after the Code for Subroutines and ScratchVariables Stabilizes

### ISSUE THREAD

**Issue by tzaffi** [algorand/pyteal#215]
## Problem

Subroutines code is undergoing significant changes and these need to be documented. The main PR's that will be affecting subroutines are:
* #198 
* #170 
* #173 (though this may not change the user interface...)
* #179 
* Other #185 issues/PR's

## Solution 

Write the docs

## Dependencies

Yes. See the above.

## Urgency

High. Useful, accurate, and up to date, docs are crucial for PyTEAL developers.

**Comment by michaeldiamant** [comment]
Closing for these reasons:
* https://github.com/algorand/pyteal/pull/226 updates the user guide to reflect `DynamicScratchVar`.
* For ABI types, we'll update the user guide again once ABI PRs stabilize and before closing out related _issues_.
* For DevRel updates reflecting `DynamicScratchVar`, I opened https://github.com/algorand/docs/issues/770 per DevRel's request.
