### ISSUE TITLE
Integrate linter:  flake8 

### ISSUE THREAD

**Issue by michaeldiamant** [algorand/pyteal#218]
## Problem

A linter like [flake8](https://flake8.pycqa.org/en/latest/) catches issues like unused imports, and lack of adherence to language standards.  It's ideal to catch these issues during the CI process because it provides a consistent approach to writing software in all parts of a repo. 

## Solution

While multiple linters exist, I propose starting with flake8 and later swapping out and/or adding others.  https://github.com/algorand/pyteal/pull/213 illustrates partial integration and can be extended.

A full solution includes:
* CI process runs flake8.
* Ensure CI and local building share the same steps.
  * Presumably, a _script_ can be written to accomplish the goal.  I'm being vague to allow freedom for interpretation. 
* Upon merge, flake8 does _not_ find errors.  Implies fixing errors for the to-be-agreed upon flake8 configuration.
* Add pyteal repo docs explaining flake8 usage.

## Dependencies

N/A

**Comment by michaeldiamant** [comment]
Consider https://github.com/bndr/pipreqs to isolate unused dependencies.  Thanks to @tzaffi for suggesting in https://github.com/algorand/pyteal/pull/249#discussion_r832680338.

**Comment by tzaffi** [comment]
That's a fine idea. Upon further investigation, one contender to `pipreqs` is [pigar](https://github.com/damnever/pigar). It seems more active than pipreqs, if not as polished.

**Comment by michaeldiamant** [comment]
FYI - I opened an issue to tracking monitoring unused dependencies because we didn't tackle it here:  https://github.com/algorand/pyteal/issues/298.
