### ISSUE TITLE
DynamicScratchVar:  User-defined DynamicScratchVars in @Subroutines produce opaque errors

### ISSUE THREAD

**Issue by michaeldiamant** [algorand/pyteal#232]
## Problem

Starting assumption:  
  * Given:  PyTeal application defines a method that meets the criteria for being annotated as `@Subroutine`.
  * When:  The application developer annotates the method with `@Subroutine`.
    * And:  Re-compiles TEAL source. 
  * Then:  Generated TEAL source _differs_ from _Given_ TEAL source, but the application _execution_  is unchanged.  
  
With the assumption in mind, consider https://github.com/michaeldiamant/pyteal/pull/3/.  
* When `retrieve_and_increment` is _not_ annotated with `@Subroutine`, PyTeal generates TEAL source.
* When `retrieve_and_increment` _is_ annotated with `@Subroute`, PyTeal fails TEAL source generation.
  * Generated error:   [test_run.log](https://github.com/algorand/pyteal/files/8186588/test_run.log)

The _problem_ might be two-fold:
* Given the starting assumption, the example ought to compile.
* The user-provided error might be too opaque to debug.  The PyTeal app developer must understand `DynamicScratchVar` compiler implementation details. 

## Solution

Several options exist:
* Attempt to enable PyTeal to complete TEAL source generation by relaxing constraints causing `set_index` error.
 
 
 https://github.com/algorand/pyteal/blob/f2598da3dec6041051df4442cd9cc7e3c373674d/pyteal/ast/scratchvar.py#L100-L105
  * My understanding is:  The constraint exists to simplify the problem space and we haven't assessed implications of loosing the constraint.
* Break the starting assumption and make no attempt to support successful compilation.  Instead, either:
  * Provide a more context aware error message to make the debugging experience easier.  For example, the error message may suggest alternative implementation options to address the issue.
  * Explicitly prevent _any_ user-defined `DynamicScratchVar` use in `@Subroutine` methods.  By constraining usage, it _might_ be easier to provide a context-aware error to the user.  

## Dependencies

N/A

## Urgency

TBD - Unclear how often users will run into the class of problem _and_ find it challenging to debug the error message.

**Comment by tzaffi** [comment]
If this is a "pure research" ticket aimed mostly at seeing the viability of just removing the warning and proposing the next steps then this should be too onerous (probably a 1-2 points).

**Comment by michaeldiamant** [comment]
@tzaffi Thanks for taking a closer look.  I reflected your findings into #242.

Closing - See #242 for rationale.
