### ISSUE TITLE
Upgrade minimum Python version to 3.10

### ISSUE THREAD

**Issue by michaeldiamant** [algorand/pyteal#244]
## Problem

Though PyTeal minimally supports Python 3.6,  on-going effort (https://github.com/algorand/pyteal/pull/222) requires access to Python 3.8.  

Since _a_ version bump is required, we'd like to use the opportunity to move to the newest minor version:  3.10 (released 10/2021).

* Rationale:  Newer language facilities simplify maintaining PyTeal.
* Underlying assumption:  It's straightforward for PyTeal developers to configure a functioning PyTeal environment by configuring a project-specific Python version. 

## Solution

We'll need to do the following:
* Provide advance community notice about the upcoming change.
* Update the build to reflect the change in minimum Python version.
* For PyTeal developer convenience, document how to configure a project-specific Python version.

## Dependencies

Provide _sufficient_ notice for the community to hear about the pending change.

## Urgency

Minimally bumping to Python 3.8 is needed to release https://github.com/algorand/pyteal/issues/185.

**Comment by algochoi** [comment]
We should also try to update the `black` version to `22.3.0` - it is the latest stable version (we pinned it down to a beta version before this) and should reformat our code with it.
