### ISSUE TITLE
ABI:  Support reference types (account, asset, and application)

### ISSUE THREAD

**Issue by michaeldiamant** [algorand/pyteal#253]
## Problem

https://github.com/algorandfoundation/ARCs/blob/main/ARCs/arc-0004.md#reference-types defines reference types accessible via _foreign arrays_ on the AVM.  To close the PyTeal ABI support gap, the ticket requests:
* Defining ARC-4 Applications with methods containing reference type parameters.
* Calling methods of ARC-4 Applications with reference type arguments.

## Solution

TBD - Consider the state of PyTeal when picking up the effort.  Consider if #254 ought to be done in tandem.

## Dependencies

* #185 
* TBD ticket for calling ARC-4 Applications.

## Urgency

TBD

**Comment by jasonpaulos** [comment]
Completed by #361
