### ISSUE TITLE
ABI:  Support transaction types

### ISSUE THREAD

**Issue by michaeldiamant** [algorand/pyteal#254]
## Problem

https://github.com/algorandfoundation/ARCs/blob/main/ARCs/arc-0004.md#transaction-types defines transaction types accessible during method invocations.  To close the PyTeal ABI support gap, the ticket requests:
* Defining ARC-4 Applications accepting transaction type parameters.
* Calling ARC-4 Applications with transaction type arguments.

## Solution

TBD - Consider the state of PyTeal when picking up the effort.  Consider if #253 ought to be done in tandem.

## Dependencies

* [#185](https://github.com/algorand/pyteal/issues/185)
* TBD ticket for calling ARC-4 Applications.

## Urgency

TBD

**Comment by jasonpaulos** [comment]
Completed by #376
