### ISSUE TITLE
ABI:  Placeholder - Support calling an ARC-4 Application

### ISSUE THREAD

**Issue by michaeldiamant** [algorand/pyteal#255]
## Problem

_Placeholder:  Expect the ticket to be broken out into multiple tickets when we pick up the effort._

https://github.com/algorandfoundation/ARCs/blob/main/ARCs/arc-0004.md defines a protocol for calling ARC-4 Applications.  To close the PyTeal ABI support gap, the ticket requests 1st class support for defining PyTeal applications calling an ARC-4 Application.

**Comment by jasonpaulos** [comment]
Completed by #387
