### ISSUE TITLE
Allow programs to use scratch space

### ISSUE THREAD

**Issue by krotkiewicz** [algorand/pyteal#32]
Hey PyTEAL maintainers,
first of all thank you for this amazing library. 

Can ask to add `ScratchSlot` examples to the documentation? Or at least here as a comment so I will be able to prepare a PR with documentation update. Thank you!

**Comment by jasonpaulos** [comment]
Hi @krotkiewicz, unfortunately it's not currently possible for programs to use scratch slots directly. They are only used to implement `MaybeValue`, which is returned by `App.localGetEx`, `App.globalGetEx`, and `AssetHolding` and `AssetParams` methods.

Would it be useful to let programs use scratch slots directly? If you can share a use case what would benefit from it, we can consider enabling that feature in a future version.

**Comment by krotkiewicz** [comment]
Thanks for a quick response. 

So yeah, we have perfect cases for that. We are designing a smart contract where we have a math operation that takes like 4 local + global + tx vars to calculate a let say a ratio that is then used in multiple places.

Currently we have to calculate this ratio value many times just to use the value then for let say multiplication or division.

I almost immediately then thought about ScratchSlot and tried to calculate that ratio value and put it in Scratch but I couldn't guess the interface for storing/loading and now I see that it is not possible.

For me the perfect interface would be to do something like that:
```python
def abc():
    tx_value = ScratchSlotNew()
    return Seq([
        tx_value.store((App.globalGet(Bytes('EXCHANGE_RATE')) * Gtxn[1].asset_amount() * Int(100 - fee_pct)) / Int(ratio_decimal_points) * Int(100)),
        Assert(tx_value.load() == Int(5)),
    ])
``` 

Similar to App.globalGet.

**Comment by jasonpaulos** [comment]
That use case makes a lot of sense, and your interface is very close to what we could support. I'll prioritize this so it gets into the next release (probably 0.6.2).

**Comment by robert-zaremba** [comment]
So PyTEAL doesn't support [load](https://developer.algorand.org/docs/reference/teal/opcodes/#load) nor `store` opcodes?

**Comment by cusma** [comment]
It does: https://pyteal.readthedocs.io/en/latest/api.html?highlight=store#pyteal.ScratchLoad

**Comment by jasonpaulos** [comment]
Actually the support is only half there. It's currently impossible to actually store something in scratch space directly from a program, but this PR will fix that: https://github.com/algorand/pyteal/pull/33
