### ISSUE TITLE
InnerTxnBuilder ABI arguments

### ISSUE THREAD

**Issue by barnjamin** [algorand/pyteal#342]
## Problem

It should be straightforward to construct a transaction or group of transactions that follow ABI spec.

At the moment all args must be manually passed with the correct encoding including remembering to set reference arguments correctly.

## Solution

Something like 
```py

#...
(arg1 := abi.Uint64).set(Int(10)),
(arg2 := abi.Account).set(Txn.accounts[0]),
(arg3 := abi.String).set(Bytes("lol")),
InnerTxnBuilder.Begin(),
InnerTxnBuilder.MethodCall(app_id, method_def, [arg1, arg2, arg3]),
InnerTxnBuilder.Next(),
#...
```

**Comment by jasonpaulos** [comment]
Completed by #361
