### ISSUE TITLE
More Efficient Scratch Slot Assignments in the ABI-Router

### ISSUE THREAD

**Issue by tzaffi** [algorand/pyteal#390]
## Problem

Consider this [PyTEAL generated approval program](https://github.com/algorand/graviton/blob/5ed03a38db14ae2c50f5e8d5d582096c56992dc5/tests/teal/router/questionable.teal#L266-L317) with companion [ABI contract](https://github.com/algorand/graviton/blob/5ed03a38db14ae2c50f5e8d5d582096c56992dc5/tests/teal/router/questionable.json). It came from this [PyTEAL compiler test](https://github.com/algorand/pyteal/blob/feature/abi/pyteal/compiler/compiler_test.py#L2198).

It specifies several methods. In particular, it defines methods `sub(uint64,uint64)uint64` and `add(uint64,uint64)uint64` that do not depend on each-other. However, PyTEAL generates TEAL code for these that enforce the usage of separate scratch slots.

For a contract with many methods, this could result in needlessly running out of slot space.

## Solution
At compile time one could partition subroutine and bare app calls based on their interdependence and then assign slots starting from 0 for each partition component.

## Dependencies

None

## Urgency

Low-Medium - it seems like very large/complex contracts would be prone to running into this issue. For example, in the above link, a contract with 10 method required 68 slots, comprising more than 1/8 of the total slot space. So a program 8 times the size would be expected to run ouf of slots. It might also be too large in general, but I don't think we want to make the number of slots block large program creation when there is no inherent need.

**Comment by jasonpaulos** [comment]
FWIW I think it's likely the case a general solution for scratch slot sharing between subroutines & mutually exclusive branches of code captures this concern. We now have another compelling use case that would benefit from it.

**Comment by gidonkatten** [comment]
Is there any update on this? I am exceeding the scratch slot limit and it is mainly being caused by many abi methods with lots of arguments

**Comment by tzaffi** [comment]
FWIW for ARC-4 compliant programs the _theoretical_ solution seems fairly straight forward. But the devil's in the details.

Basically, one would:

1. decompose the subroutine call graph as an acyclic digraph of strongly connected components (SCC's) - call this **G**
2. compute the number of slots _required_ in each SCC - this is similar to how it's currently done
3. traverse **G** starting from its leaves as follows:
  * _toVisit_ = min-heap of vertices of **G** with priority the out-degree of each vertex
  * while _toVisit_ is non-empty:
    * pop the next SCC _v_
    * assign _required(v)_ slots starting from 0 but skipping over any already assigned to SCC's for which _v_ is an **ancestor**
    * remove all edges in _G_ ending at _v_  so as to re-order _toVisit_

**Comment by tzaffi** [comment]
Closing since as of [version 8](https://github.com/algorand/pyteal/pull/562) the majority of the scratch slot usage during subroutine calls has been eliminated. @gidonkatten - if you experience any issues, please re-open.
