### ISSUE TITLE
ABI:  Add Router routing graviton tests

### ISSUE THREAD

**Issue by michaeldiamant** [algorand/pyteal#394]
## Problem

As of writing, pyteal does _not_ implement graviton tests confirming ABI Router behavior.  The story requests closing the gap by:
* Adding facilities in graviton + pyteal to support automated testing.
* Implementing at least 1 test that improves our correctness confidence.

Related:  https://github.com/algorand/graviton/pull/21 adds ABI routing tests to graviton.  It's possible to imagine extending these facilities in pyteal.

## Urgency

`compiler_test.py` offers baseline confidence because generated TEAL will change if a regression is introduced.    So, the issue seems less dire than it may initially appear.

**Comment by tzaffi** [comment]
## A couple of tasks that were mentioned in the graviton PR and are relevant to this issue:

- [ ] Add graviton ABI Routing functionality in PyTEAL via `ABIContractExecutor` and use it to test more realistic programs such as.
  - [ ] Ben's [demo abi](https://github.com/algorand-devrel/demo-abi/blob/master/contract.py) which includes _**reference**_ and _**transaction**_ type method arguments
  - [ ] Ben's [Priority Queue]

**Comment by tzaffi** [comment]
#634 which is a child pr of #600 introduces the `RouterSimulation` class and `tests/integration/abi_router_test.py` for testing the router.

I'm closing the issue now as #650 is expected to merged in to `master` in the next couple of days.
