### ISSUE TITLE
AVM 7:  Add new AVM version

### ISSUE THREAD

**Issue by michaeldiamant** [algorand/pyteal#395]
## Problem

Make PyTeal updates to support AVM 7:

* Update user guide docs. Nominally, https://pyteal.readthedocs.io/en/stable/versions.html.
* Provide https://github.com/algorand/docs/ issue for DevRel updates.
* Update MAX_TEAL_VERSION like https://github.com/algorand/pyteal/pull/146.

**Comment by barnjamin** [comment]
https://github.com/algorand/pyteal/pull/412 this takes care of bullet 3 and a few txn related attributes
