### ISSUE TITLE
Investigate Lightweight Syntax-improving Solutions

### ISSUE THREAD

**Issue by algoanne** [algorand/pyteal#396]
## Problem 
PyTeal does not have a parsing layer, and therefore the syntax is often quite unintuitive for developers. A particularly egregious example is the control flow (for, if, while) in PyTeal, but it extends to other concepts as well. 

## Solution
This ticket is for investigation only, not to carry out the work. We would like to find out if there are lightweight ways to improve the syntax that don't require adding a parsing layer. A first place to start the investigation would be by looking Tezos' [SmartPy](https://smartpy.io/docs/general/control_statements/) 's approach, which seems promising. Is it possible for us to do something like that? Are there other avenues we could explore? What exactly would undertaking this entail (i.e. provide a design doc)?

**Comment by michaeldiamant** [comment]
https://github.com/algorand/pyteal/pull/442 makes an improvement here.
