### ISSUE TITLE
Make multi-expression clauses easier in control flow statements

### ISSUE THREAD

**Issue by jasonpaulos** [algorand/pyteal#399]
## Summary

Today, when using control flow expressions like `If`, `While`, and `For`, if you want the "body" of the statement to be more than one expression, you must use `Seq` to join them, like so:

```python
If(x).Then(Seq(y1, y2, y3)).Else(Seq(z1, z2, z3))

While(x).Do(Seq(x1, x2, x3))

For(x, y, z).Do(Seq(w1, w2, w3))
```

We could make the syntax easier here by allow these methods to accept a variable number of arguments, then convert them to a `Seq` internally if necessary.

## Scope

`If`, `While`, and `For` would be affected.

Ideally we would enable this syntax, would would behave identically to the example about:

```python
If(x).Then(y1, y2, y3).Else(z1, z2, z3)

While(x).Do(x1, x2, x3)

For(x, y, z).Do(w1, w2, w3)
```

**Comment by jannotti** [comment]
How about Cond?
```
Cond([Global.group_size() == Int(5), bid, jump, run],
     [Global.group_size() == Int(4), redeem, throw, kick],
     [Global.group_size() == Int(1), wrapup])
```

**Comment by tzaffi** [comment]
Taking **kwargs for cond?

**Comment by barnjamin** [comment]
Assert too plz?

```py
Assert(
  And(....)
 )
```
 gives a pc of the last test in the conditional which isn't great for debugging
