### ISSUE TITLE
Fix incorrect use of Txn.accounts[0]

### ISSUE THREAD

**Issue by jasonpaulos** [algorand/pyteal#40]
## Summary
Some parts of the examples and documentation are wrong about how the `Txn.accounts` array works. They treat `Txn.accounts[0]` as the first element of the txn's ForeignAccounts, but actually `Txn.accounts[1]` is the first element and 0 is the sender.

## Scope
Update all examples and documentation to use `Txn.accounts` properly. Also add a section in the documentation that explicitly explains how `Txn.accounts` works.

## Urgency
Should fix ASAP so developers do not get confused.

**Comment by krotkiewicz** [comment]
We had problem with that, would apprecite quick release.

Thank you.
