### ISSUE TITLE
Downgrade to support Python 3.9

### ISSUE THREAD

**Issue by fabrice102** [algorand/pyteal#430]
## Problem

Following #244, the minimum version required for PyTeal is 3.10.

Unfortunately:
* on macOS 12 (latest version of macOS), the default Python version is 3.8.
* if using HomeBrew on macOS, the default version on Homebrew is 3.9. See https://formulae.brew.sh/formula/python@3.9#default
* on Ubuntu 20.04 (previous LTS version that is still used and that is still recommended for https://github.com/algorand/go-algorand - actually the README even says 18.05), the default Python version is 3.8 - installing a new Python requires using a ppa, which may or may not be ok in many high-security environment.

## Solution

If 3.8 / 3.9 is sufficient, why not downgrade to Python 3.8 / 3.9?
If this is not, what about adding to the installation guide (https://pyteal.readthedocs.io/en/stable/installation.html) the requirement for installing Python 3.10 with the steps to do so (at least on macOS).

## Dependencies

n/a

## Urgency

nice to have

**Comment by jasonpaulos** [comment]
We can't downgrade now that we've started to use 3.10 features (namely pattern matching), but it's certainly possible that we could offer suggestions about how to install/use the correct Python version.

**Comment by michaeldiamant** [comment]
@fabrice102 We opened https://github.com/algorand/pyteal/pull/435 to hopefully clarify the docs - feedback welcomed.  

Good point RE:  updating installation user guide.  The PR takes in the feebdack.
