### ISSUE TITLE
Asset revocation

### ISSUE THREAD

**Issue by rocinant3** [algorand/pyteal#458]
###  Hello! How to use the asset revocation feature?

<img width="634" alt="image" src="https://user-images.githubusercontent.com/42095220/180182736-ac4dfb78-4896-4cd6-8c61-61138f8f33de.png">

**Comment by barnjamin** [comment]
You'd not want to use `revocation_target` I think that is just a py-sdk construct. To clawback an asset set the asset_sender to the target that should be clawed back from.
