### ISSUE TITLE
CI:  Fail readthedocs build on warning

### ISSUE THREAD

**Issue by michaeldiamant** [algorand/pyteal#474]
## Problem

https://github.com/algorand/pyteal/pull/472 captures a readthedocs build that _silently_ fails to produce working documentation.  Since warnings do _not_ cause the build to fail, we periodically miss changes breaking docs until post-release.

The story requests the following:
* Minimally - Configure the readthedocs build to fail on warning:  https://docs.readthedocs.io/en/stable/config-file/v2.html#sphinx-fail-on-warning.  With the proposed change, we'll be alerted in Slack _after_ merging a PR to `master`.
* Optionally - Investigate how to either (a) improve the CI docs build to catch errors prior to merging or (b) hook in the readthedocs build as a PR status check.  The goal is to catch a breaking doc change _prior to_ PR merge.

**Comment by ahangsu** [comment]
does this one dup with https://github.com/algorand/pyteal/issues/327?

**Comment by michaeldiamant** [comment]
@ahangsu Indeed it does!  Closing in favor of #327.
