### ISSUE TITLE
Keccak256 doesn't generate the right hash as it should

### ISSUE THREAD

**Issue by salmanferrum** [algorand/pyteal#477]
### Subject of the issue

I passed the string “hello” to pyteal smartcontract and applied Keccak256 and it return this hash: 

`xdJGAYb3IzySfn2y3McDwOUAtlPKgic7e/rYBF2FpHA=` (base64)

If I convert it to hex using [Base64-Hex](https://base64.guru/converter/decode/hex) - this is what I received: 

`c5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470`

I have also applied the Keccak256("hello") in Javascript using 2-3 different JS Libraries: 

@ethersproject/keccak256
web.utils.keccak

And every time I received the same hash: 

`456e9aea5e197a1f1af7a3e85a3212fa4049a3ba34c2289b4c860fc0b0c64ef3`

_If you notice the hash generated from PyTeal SmartContract is completely different from the hash generated in Multiple libraries of JS._ 

After struggling from paste couple of weeks, I can conclude that the Keccak256 in Algorand doesn’t properly generate a similar hash for a simple string “hello” even though I tried all different Keccak256 libraries of JS. 

### Your environment

* Software version: `algod 3.5.1.stable`
* MacBook Pro - MacOS Montery 12.3 Beta (21E5196i)

### Steps to reproduce

1. Pass the ByteString var = "hello" to SmartContract 
2. Put the ByteString var = "hello" as a GlobalState to check if the right string is received
3. Apply Keccak256(var) 
4. Put it on the GlobalState Signed_Message to read what is received
5. Now convert the base64 hash to hex using [Base64-Hex](https://base64.guru/converter/decode/hex)
6. Verify if the right hash is received

Now Apply the same steps in Java using the above mentioned or any keccak256 libraries and the hash generated in JS will be completely different from the hash generated in Algorand. 

### Expected behaviour
The hash generated from pyteal Keccak256 should be the same as we generate using JS KECCAK256 libraries
 
### Actual behaviour

Keccak256 hash generated in JS (using different js libraries) is completely different from the hash generated in Algorand.

**Comment by jasonpaulos** [comment]
Hi @salmanferrum, I tried to replicate your results but I was unable to. Here's what I found:

I found the hash of the UTF-8 string "hello" (which is `68656c6c6f` in hex and `aGVsbG8=` in base64) using 3 different methods: the `@ethersproject/keccak256` npm library, the `js-sha3` npm library (used by the JS Algorand SDK), and by submitting an application call to the Algorand TestNet chain.

Each of these methods produced the exact same output, `1c8aff950685c2ed4bc3174f3472287b56d9517b9c948127319a09a7a36deac8` in hex, or `HIr/lQaFwu1LwxdPNHIoe1bZUXuclIEnMZoJp6Nt6sg=` in base64.

As proof, here's a transaction from TestNet which produced this same result: https://testnet.algoexplorer.io/tx/YIZYDJCH3SPDZFIV4GZ2KTBG7ZTIX3GHNRONZSMK667RUDQAYWXQ. You can see the input in the application args and the output in the global state delta.

This is the code I used to calculate the same hash using JS libraries:

```javascript
const { keccak256 } = require('@ethersproject/keccak256');

console.log(keccak256('0x68656c6c6f'));
```

```javascript
const { keccak256 } = require('js-sha3');

const hash = keccak256.create();
hash.update(Buffer.from('68656c6c6f', 'hex'));
console.log(hash.hex());
```

I believe the issue you are encountering is not related to PyTeal or the Algorand keccak256 opcode, so I'm going to close this issue.
