### ISSUE TITLE
Missing ScratchSlot.store with parameter in v0.6.2

### ISSUE THREAD

**Issue by StylishTriangles** [algorand/pyteal#49]
The added patch for version 0.6.2 (77b2e4452e443d449474d4dee1776fab3eb66f66) contains code for ScratchStore.store that accepts an extra argument

https://github.com/algorand/pyteal/blob/77b2e4452e443d449474d4dee1776fab3eb66f66/pyteal/ast/scratch.py#L13

This is however missing from the v0.6.2 release:

https://github.com/algorand/pyteal/blob/b9b0714310ab75fa4f1bc76e935fca2ff68fdaf9/pyteal/ast/scratch.py#L13

Could you please push a new version to PyPI with these changes?

**Comment by jasonpaulos** [comment]
Hi @StylishTriangles, version 0.7.0 of PyTeal will be released with these changes once #43 is done. I expect this to be relatively soon, but in the meantime you can install PyTeal directly from this repo like so:
```
pip install git+git://github.com/algorand/pyteal.git#egg=pyteal
```
