### ISSUE TITLE
Invalid TEAL program when the main program is `Cond`

### ISSUE THREAD

**Issue by fabrice102** [algorand/pyteal#5]
When the main program is `Cond`, a label is generated to jump to the end of the program. However, this is not allowed by TEAL.

For example, using the following `simple.py` script:

```python
from pyteal import *

t = Cond(
        [Int(1) == Int(1), Int(2) == Int(2)],
        [Int(3) == Int(3), Int(4) == Int(4)]
        )

print(t.teal())
```

We have:
```bash
$ python3 simple.py > simple.teal
$ goal clerk send --from-program simple.teal --to GCBRBIIMS7IVTHC3Y7ML6WAGGPK4L3LVSHDWXPTMD5YO2E7CFWNN5X2KOE --amount 10
Couldn't broadcast tx with algod: HTTP 400 Bad Request:  32 bnz target beyond end of program
```

where `simple.teal` is:
```
int 1
int 1
==
bnz l0
int 3
int 3
==
bnz l1
err
int 1
bnz l2
pop
l1:
int 4
int 4
==
l2:
int 1
bnz l3
pop
l0:
int 2
int 2
==
l3:
```

One solution would be to add a no-op at the end. There does not seem any single-op no-op in TEAL currently, but it can be simulated using a double op:
```
dup
pop
```

**Comment by jasonpaulos** [comment]
This will be fixed when LogicSig v2 support is merged in, since v2 allows jumping to the end of programs. In the meantime, you can also wrap your program with `Or(<program>, Int(0))`  as a workaround.

For example:
```python
t = Cond(
        [Int(1) == Int(1), Int(2) == Int(2)],
        [Int(3) == Int(3), Int(4) == Int(4)]
        )

t_prime = Or(t, Int(0))

print(t_prime.teal())
```
Which generates:
```
int 1
int 1
==
bnz l0
int 3
int 3
==
bnz l1
err
int 1
bnz l2
pop
l1:
int 4
int 4
==
l2:
int 1
bnz l3
pop
l0:
int 2
int 2
==
l3:
int 0
||
```
