### ISSUE TITLE
Operator overloading for Concat and Bytes

### ISSUE THREAD

**Issue by PabloLION** [algorand/pyteal#563]
## Problem

`Bytes('a') + Bytes('b')` will report type check error because of this: https://github.com/algorand/pyteal/blob/master/pyteal/ast/expr.py#L72-L73

https://github.com/algorand/pyteal/blob/1a1c93f35ffdad1136ddf81d6c5d5a0ca510cabd/pyteal/ast/expr.py#L72-L73

## Solution

`Bytes('a') + Bytes('b')` returns `Concat(Bytes('a'),Bytes('b'))`, or `Bytes('ab')`

## Urgency

Ergonomic feature, not urgent.

**Comment by barnjamin** [comment]
dupe of https://github.com/algorand/pyteal/issues/496

**Comment by PabloLION** [comment]
Sorry @barnjamin
