### ISSUE TITLE
Prototype:  Feature gate support

### ISSUE THREAD

**Issue by michaeldiamant** [algorand/pyteal#601]
## Problem

Taking inspiration from https://blog.rust-lang.org/2014/10/30/Stability.html, we'd like to prototype a feature gating mechanism like https://rustc-dev-guide.rust-lang.org/feature-gates.html.  A feature gating system is one way for PyTeal to support faster velocity with fewer support guarantees while not sacrificing quality. 

The story's intent is to gauge implementation + maintenance challenges associated with supporting a feature gating system in PyTeal.  At the story's conclusion, we'd like to make a yes/no decision on supporting the approach as part of instituting a broader stability policy.

The feature gating mechanism does _not_ need to mirror Rust exactly.  Criteria we want to support include:
* Define a way to demarcate modules, classes, methods, and variables as experimental.  Access to experimental capabilities is controlled by PyTeal release version.  Only non-final (e.g. nightly builds, branch builds) versions can access experimental capabilities. 
* Optionally, providing an explicit opt-in mechanism to use experimental features.

It's understood that we'll negotiate the effort while underway.  We may realize some objectives are untenable.  Ultimately, if the approach isn't tenable, we want to gauge where to go next.

## Solution

Compiling links that may be helpful:
* https://stackoverflow.com/questions/8951787/defining-python-decorators-for-a-complete-module - The approach described here _might_ benefit our own implementation.
* https://github.com/carta/flipper-client - Example Python feature flag library.  It _might_ help us brainstorm our own approaches.

**Comment by tzaffi** [comment]
I ran into a related consideration in #552 . The PR is proposing to enable a new feature -source mapping- while having it unavailable -by default. To turn the feature on, someone who clones the repo, or a depending library (in my case [Beaker](https://github.com/algorand-devrel/beaker/pull/117/files)) needs to explicitly set a config variable _**on**_ in the [introduced pyteal.ini](https://github.com/algorand/pyteal/blob/a59e4b678eace2a9c80ec83d417b00bfe3020fed/pyteal.ini):

<img width="196" alt="image" src="https://user-images.githubusercontent.com/291133/201776228-0f74ea8c-86a8-443e-9065-cbc6c6637c41.png">

I'm not sure the approach I took is the perfect solution. There were some definite downsides:
* I needed to assert that the feature was turned on, before attempting to use it
* I needed to introduce tests that asserted that the feature was off by default
* For tests of the actual feature, I needed to monkeypatch the config to fool the test into believing that the feature was on
* If the feature is ever promoted, I will need to remove the monkeypatching

**Comment by tzaffi** [comment]
#686 proposes a new package `feature_gates` that should be able to handle most of the requirements. Still in flux is whether it will use the file system as a backup for configuration, or manage the gates purely in code.

**Comment by tzaffi** [comment]
@bbroder-algo 

#686 proposes a new package `feature_gates` that should be able to handle most of the requirements. Still in flux is whether it will use the file system as a backup for configuration, or manage the gates purely in code.
