### ISSUE TITLE
PyTeal examples folder ships with the package itself

### ISSUE THREAD

**Issue by CiottiGiorgio** [algorand/pyteal#608]
Not sure if this was intended or not but I think the examples shouldn't be shipped with the package.
I observed the same behaviour in `beaker` and it is currently being addressed by [this](https://github.com/algorand-devrel/beaker/issues/132) issue.

**Comment by jasonpaulos** [comment]
Hi @CiottiGiorgio, why do you think examples should not ship with the package?

**Comment by CiottiGiorgio** [comment]
I think it can be nice if you are working directly with PyTeal but if I'm just importing it as a dependency (of Beaker for example) I don't need PyTeal examples.
As it is named right now, it's just an `example` folder within `site-packages` and it could collide with other examples from other packages (should they also ship them).
The best place is probably in a separate python package and then listed in the dev dependencies of pyteal (alongside testing, typing and formatting utilities that are currently written in `requirements.txt` and not `install_requires`).

At the very least, the folder should be called `pyteal_examples` so it does not collide with other dependency in the project.

**Comment by CiottiGiorgio** [comment]
While I was figuring out the structure of the project and how it installs dev/non-dev dependencies, I found found out that we have the same issue for `tests` in `PyTeal` package and `tests` in `py-algorand-sdk` package. Both `tests` folders end up in `site-packages` colliding with each other.
Personally, I would set `packages` into `setup.py` to just `packages=["pyteal"]` and do the same for `py-algorand-sdk`.

**Comment by CiottiGiorgio** [comment]
#610 is my proposal

**Comment by CiottiGiorgio** [comment]
#610 was merged so we can close this.

**Comment by michaeldiamant** [comment]
For completeness - A bug in #610 was corrected via https://github.com/algorand/pyteal/pull/614.
