### ISSUE TITLE
Issue with Itob function in PyTEAL

### ISSUE THREAD

**Issue by moon-gazer** [algorand/pyteal#62]
Consider the following:

Statement 1:
App.globalPut(Concat(Bytes("1"), Bytes("data_")), Int(1))

Statement 2:
App.globalGet(Concat(Itob(Int(1)), Bytes("data_")))

Statement 2 results in an error:
"type of data is incorrect. Expected object but got bigint at line 325"

To isolate this error, we tried it in an isolated environment and it results in a similar error.
Could you please help with this.

**Comment by jasonpaulos** [comment]
Hi @moon-gazer, could you please provide a small runnable python file that shows this error? Also, which version of PyTeal are you using?

**Comment by moon-gazer** [comment]
We are using PyTEAL 0.7.0

The following is the code (Stripped down code to isolate the error):

from pyteal import *

TRANSACTION_TYPE_DEPOSIT_ALGO = Bytes("da")


def approval_program():    

    on_create = Seq(
        [
            App.globalPut(Concat(Bytes("1"), Bytes("sample_")), Int(1)),
            Int(1),
        ]
    )

    on_closeout = Int(1)

    on_opt_in = Int(1)

    on_deposit = App.globalGet(Concat(Bytes(Itob(Int(1))), Bytes("sample_")))

    program = Cond(
        [Txn.application_id() == Int(0), on_create],
        [Txn.on_completion() == OnComplete.CloseOut, on_closeout],
        [Txn.on_completion() == OnComplete.OptIn, on_opt_in],
        [Txn.application_args[0] == Bytes("dp"), on_deposit],
    )    
    return program


if __name__ == "__main__":
    print(compileTeal(approval_program(), Mode.Application))
    with open("./assets/main_approval.teal", "w") as f:
        f.write(compileTeal(approval_program(), Mode.Application))

The contract creation is successful as expected, however, when a contract call is made with the appArgument "da" as a string, it will throw the error I mentioned before.

**Comment by jasonpaulos** [comment]
@moon-gazer I believe the problem is this line:
```python
on_deposit = App.globalGet(Concat(Bytes(Itob(Int(1))), Bytes("sample_")))
```

You should only pass string constants into the `Bytes` constructor, but `Itob(Int(1))` is a dynamic pyteal expression.

It should instead be:
```python
on_deposit = App.globalGet(Concat(Itob(Int(1)), Bytes("sample_")))
```

Unrelated: are you aware that `Itob` does not convert integers to human-readable strings? E.g. `Itob(Int(1))` will not equal `"1"`. See the docs: https://pyteal.readthedocs.io/en/stable/data_type.html#conversion

**Comment by Lumene98** [comment]
> 
> 
> @moon-gazer I believe the problem is this line:
> 
> ```python
> on_deposit = App.globalGet(Concat(Bytes(Itob(Int(1))), Bytes("sample_")))
> ```
> 
> You should only pass string constants into the `Bytes` constructor, but `Itob(Int(1))` is a dynamic pyteal expression.
> 
> It should instead be:
> 
> ```python
> on_deposit = App.globalGet(Concat(Itob(Int(1)), Bytes("sample_")))
> ```
> 
> Unrelated: are you aware that `Itob` does not convert integers to human-readable strings? E.g. `Itob(Int(1))` will not equal `"1"`. See the docs: https://pyteal.readthedocs.io/en/stable/data_type.html#conversion

Is it possible to get a human-readable string from a uint64? Even concatenating multiple function

**Comment by moon-gazer** [comment]
Apologies, we intended to try it as the below only.

`on_deposit = App.globalGet(Concat(Itob(Int(1)), Bytes("sample_")))`

but as you mentioned even this is not supposed to work.
I will tell you the actual problem.

So basically there is an app (smart contract) to which an account is making a call.
The calls gives it 2 variables, which can be visualized as a (key, value) pair.

Hence we try something like

`App.globalPut(Concat(Itob(Txn.application_args[1]), Bytes("sample_")), Txn.application_args[2]),`

Where the appArgs at both the indices 1 and 2 are integers. Txn.application_args[1] is an asset ID belonging to an asset.

When we do

`App.globalGet(Concat(Txn.xfer_asset()), Bytes("sample_")))
`
We are unable to retrieve the desired variable stored previously.

Any idea why this is not working?

**Comment by jasonpaulos** [comment]
> Is it possible to get a human-readable string from a uint64 even concatenating multiple function? Or we have to use bit/bytes manipulation? Also is it normal that `Concat(Bytes("1"), Bytes("2"))` return `21` instead of `12` ?

@Lumene98 there is no built-in way to generate human readable strings from numbers. This is because it's not recommended to store human-readable values as state in the blockchain; your front-end should convert values to a human-readable form. However, if you really need this, you can definitely try to create TEAL code to stringify ints.

Also, `Concat(Bytes("1"), Bytes("2"))` should produce `"12"`. If you are seeing something different, please share.

**Comment by jasonpaulos** [comment]
> Apologies, we intended to try it as the below only.
> 
> `on_deposit = App.globalGet(Concat(Itob(Int(1)), Bytes("sample_")))`
> 
> but as you mentioned even this is not supposed to work.
> I will tell you the actual problem.
> 
> So basically there is an app (smart contract) to which an account is making a call.
> The call gives it 2 variables, which can be visualized as a (key, value) pair.
> 
> Hence we try something like
> 
> `App.globalPut(Concat(Itob(Txn.application_args[1]), Bytes("sample_")), Txn.application_args[2]),`
> 
> Where the appArgs at both the indices 1 and 2 are integers. Txn.application_args[1] is an asset ID belonging to an asset.
> 
> When we do
> 
> `App.globalGet(Concat(Itob(Txn.xfer_asset())), Bytes("sample_"))) `
> We are unable to retrieve the desired variable stored previously.
> 
> Any idea why this is not working?

The elements of `Txn.application_args` will always be bytes, so there is no need to use `Itob` on them -- in fact, this should give you a compile error.

What do you mean by "We are unable to retrieve the desired variable stored previously."? Is there an error, or do you get a value you do not expect?

**Comment by Lumene98** [comment]
> > Is it possible to get a human-readable string from a uint64 even concatenating multiple function? Or we have to use bit/bytes manipulation? Also is it normal that `Concat(Bytes("1"), Bytes("2"))` return `21` instead of `12` ?
> 
> @Lumene98 there is no built-in way to generate human readable strings from numbers. This is because it's not recommended to store human-readable values as state in the blockchain; your front-end should convert values to a human-readable form. However, if you really need this, you can definitely try to create TEAL code to stringify ints.
> 
> Also, `Concat(Bytes("1"), Bytes("2"))` should produce `"12"`. If you are seeing something different, please share.

Thanks! I realized that the concat problem is algob related I'm gonna bring that to them

**Comment by moon-gazer** [comment]
@jasonpaulos 
Should the below work if Txn.application_args is ['int:2'] and Txn.xfer_asset() is also 2?

from pyteal import *

def approval_program():    

    on_create = Seq([
        App.globalPut(Concat(Txn.application_args[0], Bytes("test_")), Btoi(Txn.application_args[0])),
        Int(1),
    ])

    on_closeout = Int(1)

    on_opt_in = Int(1)

    on_test = App.globalGet(Concat(Itob(Txn.xfer_asset()), Bytes("test_")))

    program = Cond(
        [Txn.application_id() == Int(0), on_create],
        [Txn.on_completion() == OnComplete.CloseOut, on_closeout],
        [Txn.on_completion() == OnComplete.OptIn, on_opt_in],
        [Txn.type_enum() == TxnType.AssetTransfer, on_test],
    )    
    return program

if __name__ == "__main__":
    print(compileTeal(approval_program(), Mode.Application))
    with open("./assets/main_approval.teal", "w") as f:
        f.write(compileTeal(approval_program(), Mode.Application))

Steps:
1. create the asset
2. create the app
3. account opts in to app
4. send the asset (throws an error: "type of data is incorrect. Expected object but got bigint at line 325")

**Comment by jasonpaulos** [comment]
@moon-gazer that program looks like it should run properly

**Comment by moon-gazer** [comment]
> @moon-gazer that program looks like it should run properly

Yes, it does. We think the issue is with scale-it algo-builder (we were using their Runtime to create the transactions), hence we have raised the issue there. Thanks a lot for your prompt responses and help :-)
