### ISSUE TITLE
Pyteal not compatible with `py-algorand-sdk=2.0.0`

### ISSUE THREAD

**Issue by DamianB-BitFlipper** [algorand/pyteal#633]
## Problem

In a project which requires both `pyteal` and `py-algorand-sdk`, the dependency resolver solves for the latest version of `pyteal`, but that forces `py-algorand-sdk<2`. This mean I cannot make use of the new features of `algosdk` introduced in v2. As a temporary patch, I have `pyteal` pinned to `<=0.13.0` before the `py-algorand-sdk<2` was in place (though this is likely a problematic way to approach things). 

## Solution

I do not know how involved it is, but it would be nice to have `pyteal` compatible with the latest `py-algorand-sdk`. I was surprised at first since I expected it to work since these libraries pertain to the same Algorand ecosystem.

## Urgency

Moderate, since as it stands `py-algorand-sdk` does not work with any version of `pyteal`, except for old versions, which is likely not intended/recommended.

**Comment by ahangsu** [comment]
A little big more context: we did up the lower limit of py-sdk version in one of the latest commits https://github.com/algorand/pyteal/pull/626, but the py-sdk version up is not yet released on pyteal side.

We will have this issue resolved once pyteal have a release for recent changes.

**Comment by ahangsu** [comment]
closing for new release https://github.com/algorand/pyteal/releases/tag/v0.21.0
