### ISSUE TITLE
Unittests?

### ISSUE THREAD

**Issue by ManuelZierl** [algorand/pyteal#64]
I've already asked a similar question on the algorand developer forum here: https://forum.algorand.org/t/test-contracts-

I’ve lately started learning to develop smart contracts with TEAL on the algorand blockchain with pyteal and i really like it but i have noticed that the workflow for testing (especially unittesting) is very inconvenient. Publishing an app every time on the test net is very time-consuming and running a private network was also very difficult and cumbersome.

Wouldn't it be nice to have the possibility of testing inside the pyteal framework which allows us simultaneously mocking things like the arguments, global, local state, addresses and co. Obviously this would not replace testing on the testnet but would be a lot more convenient during development since it would be possible to also write test for partial code

If this is for some reason a stupid/unuseful idea you can obviously delete this issue, but would be nice to here your opinion about this idea. 

If something like this is of interest for pyteal i would offer my help for development (since i'm new to the algorand ecosystem help would be appreciated ;) )

**Comment by jdtzmn** [comment]
Hi @ManuelZierl, I'm happy to let you know that such functionality already exists within algod! You can use the `/v2/teal/dryrun` endpoint to execute TEAL programs within a defined context and receive a response which contains debugging information about the execution ([docs](https://developer.algorand.org/docs/reference/rest-apis/algod/v2/#post-v2tealdryrun)). While testing inside the PyTeal framework would be nice, I think from a maintainability and consistency standpoint it makes more sense to use the existing dryrun mechanism for testing.

To help get you started, here's [a gist](https://gist.github.com/jdtzmn/6ea59d25f34c21c7ed4158a3f62b5cd5) with the dryrun testing setup I use for testing my PyTeal projects. The gist includes a dryrun testing library I wrote that helps construct the context sent to the dryrun endpoint, as well as other helpers that come in handy when dryrun testing with a testing framework like [Jest](https://jestjs.io/).

> **Note:** Dryrun testing requires access to an algod instance. I highly recommend setting up a local algod instance using the [Algorand sandbox](https://github.com/algorand/sandbox).

**Comment by ManuelZierl** [comment]
@jdtzmn, thanks for your detailed explanation and the links, I'll have a look into it. I was actually hoping for some solution that doesn't require running an entire Algorand chain ;), but obviously I get your point about  maintainability and consistency!

**Comment by jdtzmn** [comment]
@ManuelZierl I can understand that running an entire Algorand chain can be unwieldy. If it helps, the Algorand sandbox can run a [private network](https://github.com/algorand/sandbox#private-network), which means no waiting for the node to catch up and minimal storage requirements. Private sandbox networks can be started more quickly than typical Algorand nodes and can even be run from within popular CIs.
