### ISSUE TITLE
Source Mapper: Poor Mapping of Subroutines

### ISSUE THREAD

**Issue by tzaffi** [algorand/pyteal#658]
### Upcoming Source Mapper Feature: not mapping subroutines correctly

When source mapping is enabled and annotated teal generated, *Subroutine/AbiSubroutine/router.method* definitions and calls are not mapped correctly (or at least inconsistently). 

For example, @bbroder-algo generated a source map for code residing in [this repo](https://github.com/gr8h/project_rps) (this is the "Rock Paper Scissors" example from a [recent bootcamp](https://medium.com/encode-club/encode-x-algorand-bootcamp-december-2022-summary-d7daf118b8b6)), and obtained this snippet:

<img width="898" alt="image" src="https://user-images.githubusercontent.com/291133/216179188-c4dcdb30-9956-420e-8cab-ccbaff4c7f3c.png">

We can see that there were two subroutines `reset` (starting line 85) and `is_account_empty` (starting line 114). However:
* the beginning of the definitions (`// reset` and `// is_account_empty`) were mapped to `Compilation(...`
* the ending of the definitions (`retsub` on lines 110 and 152 -not shown-) were also mapped to `Compilation(...`

Note that a mapping to `Compilation(...` basically indicates a source-mapper _MISS_. 

### Expected behaviour

The beginning and end of each `@Subroutine` and `@ABIReturnSubroutine` and `@router.method` definition should display
the python signature of the function that was decorated.  So in the case of `reset` above, it should have looked like:

```python
// reset                          //                        19      def reset(account: Expr):
reset_0:                          //
store 0                           //
load 0                            //
byte "opponent"                   //                        9       Bytes('opponent')

...

app_local_put                     //                                App.localPut(account, local_play, Bytes(''))
retsub                            //                        19      def reset(account: Expr):
```

### Actual behaviour

Unfortunately, it looks more like the following currently:

```python
// reset                          //                        249     Compilation(approval_program(), Mode.App...
reset_0:                          //
store 0                           //
load 0                            //
byte "opponent"                   //                        9       Bytes('opponent')

...

app_local_put                     //                                App.localPut(account, local_play, Bytes(''))
retsub                            //                        249     Compilation(approval_program(), Mode.App...
```

**Comment by tzaffi** [comment]
## Question

Should we actually map the `retsub` to the final line in the subroutine, as opposed to its definition?

**Comment by bbroder-algo** [comment]
I suppose the definition is better since it provides more debugging context, especially if the teal generation gets more clever.

**Comment by tzaffi** [comment]
With a recent commit, I believe this issue is resolvable: https://github.com/tzaffi/pyteal/blob/7f8addfe2de34b6f214107b4c90ec8e97bcd3ac6/tests/teal/rps_annotated.teal#L70-L90

Further improvements to the router _such as replacing "misses" inside the subroutine execution by the associated subroutine signature_ are anticipated in #676

**Comment by bbroder-algo** [comment]
nice 676 is a good idea
