### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by lanaradmilovic** [algorand/pyteal#699]
![A6459C7D-EBE7-4B10-B761-61A877476624](https://user-images.githubusercontent.com/115712547/230378208-daa7949c-2798-41c9-a391-9eab36a36217.jpeg)
I run into this problem while trying to bash test.sh file using command bash /data/tests/test.sh. Does it look familiar to anyone?

**Comment by jasonpaulos** [comment]
Hi @lanaradmilovic, I'm not familiar with the `/data/tests/test.sh` file you're referencing -- is this something you've written to test your own smart contracts?

The error `transaction rejected by ApprovalProgram` indicates that the contract did not approve the application call. If you think this is unexpected, please share the contract code and how you're invoking it.
