### ISSUE TITLE
Change Will's algod to Algorand's algod image

### ISSUE THREAD

**Issue by ahangsu** [algorand/pyteal#704]
Reminder: We are currently (2023/04/18) using Will's algod image under `dev` label, ultimately we want to use Algorand's image.

Some changes in CI configuration need to be made: we need a `config.json` with `EnableDeveloperAPI: true` activated, and override before we run the image, see: https://github.com/algorand/go-algorand/tree/master/docker#special-files

**Comment by jasonpaulos** [comment]
Closed as part of #713
