### ISSUE TITLE
EcPairingCheck Bug in PyTeal Version 0.26 - Expected uint64, Returns bytes

### ISSUE THREAD

**Issue by mangoplane** [algorand/pyteal#716]
### Subject of the issue

`EcPairingCheck` Bug in PyTeal Version 0.26

### Your environment

- PyTeal version: 0.26
- Algod version: Latest `algorand/algod:stable` docker image
- Operating System: Windows 11

### Steps to reproduce

1. Use `EcPairingCheck` in a PyTeal program
2. Observe the type of value returned by `EcPairingCheck`

### Expected behaviour

`EcPairingCheck` should return a boolean value (0 or 1) as a `uint64` type.

### Actual behaviour

The implementation returns an `EcPairingCheck` expression of type `bytes`. The underlying AVM opcode it wraps returns a value of type `uint64`, which it must reflect.

**Comment by jasonpaulos** [comment]
Thank you for the report, I can confirm this is a bug

**Comment by jasonpaulos** [comment]
A fix for this has been released in v0.26.1
