### ISSUE TITLE
Support importing/exporting values between contracts

### ISSUE THREAD

**Issue by jasonpaulos** [algorand/pyteal#74]
# Summary
TEAL v4 introduces the `gload(s)` ops, which can load values from the scratch space of prior app call transactions in the same group. PyTeal should support this feature as well.

# Scope
edit: commenting out the initial idea in favor of a simpler approach inspired by @StylishTriangles's suggestion.

This issue requires the following changes:

1. Allow `ScratchSlot` to have an additional optional parameter `requestedSlotId`, which would be an integer from 0-255 which specifies the slot ID that compiler **must** assign to this slot. This would also require modifications to `compileTeal` to actually assign the correct ID to any `ScratchSlot`s with this parameter, and if multiple unique `ScratchSlot` request the same slot ID, compilation must fail.
2. Also add an optional `requestedSlotId` parameter to `ScratchVar` which would be passed directly to its underlying `ScratchSlot`.
3. Expose the `gload` op in a PyTeal expression (maybe as `ImportScratchValue(txnIndex: Expr, slotId: int)`)

~Ideally we can have a system where one contract can export many values (perhaps with helpful names that don't make it onto the chain) with something like `Export("bidAmount", computedBidAmount)`. Then, another contract can import this exported value with something like `computedBidAmount = ImportFrom(txnIndex, contract1.exports("bidAmount"))`.~

~This would require programs to be compiled in a specific order to make dependencies work, or all at once and the compiler can sort out dependencies.~

~Additionally, the compile method would need to return more information, perhaps a Python object that contains a dict of all exports from the contract and their assigned slots -- it's important to make this information accessible by the user so that they can properly debug, and it also lets other non-PyTeal contracts import their exports. This object then needs to be obtained by the importing contract in order to know which slots to actually load. Again, here it will be important to allow imports from non-PyTeal contracts (meaning essentially direct access to gload(s)).~

**Comment by StylishTriangles** [comment]
Wouldn't it be easier to let developers specify scratch slot ID that they wish to use?
For example contract1.py could have
`bid_amt = ScratchSlot(slot_id=211) `
Then in contract2.py you could just use
`computed_bid_amt = GLoad(0, 211)`
This would be rather convenient to use and would avoid the hassle of multi-compilation/passing around complex objects.

**Comment by jasonpaulos** [comment]
@StylishTriangles thanks for the suggestion, that may be a simpler alternative.
